; PlatformIO Project Configuration File

[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino
board_build.partitions = huge_app.csv
build_flags = 
	-DBOARD_HAS_PSRAM
	-DCORE_DEBUG_LEVEL=0
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps = 
	espressif/esp32-camera
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
upload_port = COM5
monitor_port = COM5